name: Deploy Website2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Website2 to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_SERVER }}
        username: ${{ secrets.USER_SERVER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/website2
          git pull origin main
          sudo systemctl reload nginx
